### ISSUE TITLE
Building is incompatible with CMake 3.10.2

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-cdt#14]
CMake 3.10.2 ships with Ubuntu 18.04 LTS.  It stops with an error message:

```
CMake Error in koinos_api_cpp/CMakeLists.txt:
  No known features for CXX compiler    "Clang"  version 10.0.0.
```

As stated [here](https://cmake.org/cmake/help/v3.10/manual/cmake-compile-features.7.html) CMake version 3.10.x only supports a limited range of CMake versions with an upper limit.  This upper version limit seems to have been removed [as of CMake 3.16](https://cmake.org/cmake/help/v3.16/manual/cmake-compile-features.7.html) which is fortunately the version of CMake that ships with Ubuntu 20.04 LTS.

I'd suggest bumping `cmake_minimum_required` to `3.16.0` to fail quickly and cleanly if using an older CMake.

This experience suggests it may be reasonable to include CMake in the CDT instead of relying on host CMake.  Thoughts?

**Comment by mvandeberg** [comment]
We are not currently making an effort to support 18.04
